Open project with Unity2018.1.5f1(64bit)
Open project with Unity2018.1.5f1(64bit)
fix error
Assets/Plugins/Unity-Logs-Viewer/Reporter/Reporter.cs(2013,47): error CS0619: `UnityEngine.RuntimePlatform.OSXWebPlayer' is obsolete: `WebPlayer export is no longer supported in Unity 5.4+.'